var Producto = document.getElementById("Producto")
var Nombre_completo = document.getElementById("Nombre_completo")
var Direccion = document.getElementById("Direccion")
var Cantidad = document.getElementById("Cantidad")
var Telefono = document.getElementById("Telefono")
